# Generated by Django 2.1.7 on 2019-03-13 20:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 13, 20, 53, 36, 498258, tzinfo=utc)),
        ),
    ]
