# Generated by Django 2.1.7 on 2019-03-16 23:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190315_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 16, 23, 51, 58, 585561, tzinfo=utc)),
        ),
    ]
